### ISSUE TITLE
penjelasan mengenai requirement di readme

### ISSUE THREAD

**Issue by titounnes** [slims/slims8_akasia#105]
setelah berkutat agak lama, saya akhirnya berhasil install senayan akasia diserver dengan spesifikasi sbb
os centos 7
webserver nginx
php versi 7.2.x
database mariadb
di awal saya mengalami kendala dengan gettext yg tidak lazim.
umumnya gettext menggunakan _('foo') bukan __('foo'), informasi yg muncul saat instalasi pun hanya error 500
saya coba cari tulisan mengenai problem ini dan tidak ada satu informasi yg memuaskan.
akhirnya setelah saya coba menggunakan cli, tutuk cerah mulai muncul
rupanya sistem ini membutuhkan php-mbstring, dan itu tidak ada dalam peringatan saat instalasi.
Mohon, requirement dituliskan dalam readme sehingga memudahkan instalasi di server yg tidak menggunakan paket instalasi seoerti xampp.

**Comment by buitenzorg812** [comment]
terima kasih atas sarannya. akan kami tambahkan dalam README atau pengingat dalam installer.

**Comment by buitenzorg812** [comment]
pengingat dalam installer sudah ditambahkan. semoga bermanfaat.

**Comment by titounnes** [comment]
sukses selalu mas..
