### ISSUE TITLE
Compact dashboard page

### ISSUE THREAD

**Issue by buitenzorg812** [slims/slims8_akasia#157]
Tampilan laman dashboard dibuat kompak, tanpa harus menggulung layar laman dashboard, untuk melihat bagian bawah yang tidak perlu.

![screenshot from 2018-12-28 00-35-30](https://user-images.githubusercontent.com/125229/50489422-27957d00-0a3a-11e9-950d-4be273bca0ae.png)

**Comment by idoalit** [comment]
@buitenzorg812 Kayaknya susah & kurang recommend, mengingat ukuran layar berbeda beda dan konten didalamnya yg dinamis.

**Comment by buitenzorg812** [comment]
> @buitenzorg812 Kayaknya susah & kurang recommend, mengingat ukuran layar berbeda beda dan konten didalamnya yg dinamis.

oke siap mas. diclose aja tiketnya ya.
