### ISSUE TITLE
Uncaught ReferenceError: google is not defined

### ISSUE THREAD

**Issue by drwwjy** [slims/slims8_akasia#177]
Muncul pesan:
Uncaught ReferenceError: google is not defined

![image](https://user-images.githubusercontent.com/50572885/57605217-c0b3d300-7598-11e9-8b3d-409f3ae84b0e.png)

Errornya dmn ya? Tolong, ada yang bisa bantu?

**Comment by buitenzorg812** [comment]
bisa tolong diceritakan kronologi kejadian sehingga pesan galat tersebut muncul?

**Comment by drwwjy** [comment]
ini memakai template bootstrap_4 dari web perpustakaan Yudharta Pasuruan
[http://perpustakaan.yudharta.ac.id/2018/04/17/template-opac-slims-akasia-bootstrap-4/]

**Comment by buitenzorg812** [comment]
monggo dikonsultasikan ke pengembang templat yang bersangkutan.

**Comment by drwwjy** [comment]
baik. makasih buat informasinya
