### ISSUE TITLE
Book cover tidak muncul di record detail

### ISSUE THREAD

**Issue by alveolusss** [slims/slims8_akasia#181]
Saya sudah coba install slims akasia offline dan semua berjalan normal, namun ketika saya coba install di hosting untuk cover book di bagian record detail foto nya tidak muncul, apakah ada yang saya lewat kan?

![error](https://user-images.githubusercontent.com/4488498/60643523-8ca0b400-9e5d-11e9-8c3c-d0d6ce14b3ab.PNG)

**Comment by ndutndutan** [comment]
saya juga mengalami hal yang sama mas, belum solved

**Comment by alveolusss** [comment]
Sudah coba hal apa saja mas? saya coba ganti versi php juga masih bermasalah

**Comment by ndutndutan** [comment]
saya sudah kasih pemision ke folder files images  dan repository mas..ada info dari pengguna slims juga, katanya itu bergantung hostingnya mas..

**Comment by alveolusss** [comment]
seperti itu ya, baiklah saya coba komunikasikan dengan provider. Thanks mas.
