### ISSUE TITLE
Tampilan slim admin

### ISSUE THREAD

**Issue by alimoddin123** [slims/slims8_akasia#199]
You are logged in as Super User. With great power comes great responsibility.

kalau mengatsi ini gmn yy?

**Comment by alimoddin123** [comment]
yang kedua mencul seperti ini 

Error requesting page : /admin/modules/master_file/publisher.php?ajaxload=1undefined
Press F5 to hide this error message.

**Comment by idoalit** [comment]
> You are logged in as Super User. With great power comes great responsibility.
> 
> kalau mengatsi ini gmn yy?

apakah ada error disitu? Background merah bukan berarti semuanya adalah error.

> yang kedua mencul seperti ini
> 
> Error requesting page : /admin/modules/master_file/publisher.php?ajaxload=1undefined
> **Press F5 to hide this error message.**

Bukannya sudah cukup jelas?

Saran saja, coba gunakan google translate kalau tidak paham artinya
