### ISSUE TITLE
deleted loan rules

### ISSUE THREAD

**Issue by buitenzorg812** [slims/slims8_akasia#20]
please do make check, concerning loan rules attached to circulation. because we have a concern here. when someone make a loan rules then make a lend based on that loan rules, that loan rules bind to that person. but when that someone erase that particular loan rules, all data related to erased loan rules, will be gone to. and the admin will be confused.

please do make check.

**Comment by idoalit** [comment]
@buitenzorg812 Berarti tidak bisa di delete jikalau rule tsb ada yg makek ya?

**Comment by buitenzorg812** [comment]
hnah...harusnya begitu. ada semacam warning.

**Comment by slims** [comment]
@buitenzorg812 Kejadian di Untirta

**Comment by buitenzorg812** [comment]
kejadian jugak di salah satu pengguna SLiMS yang curhat di forum.

**Comment by buitenzorg812** [comment]
jadi terkait isu ini gimana, apakah bisa dikunci, apabila ada rules yang terpakai oleh proses transaksi?

**Comment by wynerst** [comment]
@buitenzorg812 Kalau mau slims akuntable terkait denda (tidak hanya denda tapi semua transaksi) maka menurut says harusnya ditambahkan fasilitas untuk tetap menyimpan semua aturan pinjam selama diperlukan/dibutuhkan jika ada pemeriksaan.

**Comment by buitenzorg812** [comment]
@wynerst hajar mas

**Comment by buitenzorg812** [comment]
jadi gimana ini, apakah sudah bisa dieksekusi? supaya masalahnya nggak berkelanjutan

**Comment by slims** [comment]
Udah diperbaiki? Belum yak.

**Comment by buitenzorg812** [comment]
updated by @hendrowicaksono
