### ISSUE TITLE
Slims Module

### ISSUE THREAD

**Issue by ardani** [slims/slims8_akasia#3]
Hallo guys. dev senayan
mau tanya , panduan pembuatan module tambahan (custom) untuk slims 8  ada gak ?

**Comment by idoalit** [comment]
Pembuatan module baru bisa dilakukan dengan: 

- [x] Mebuat folder baru (misalkan `plugins`) di dalam folder `<slims_root_directory>/admin/modules`
- [x] Tambahkan file `index.php` serta `submenu.php` didalam folder tersebut.
- [ ] Login ke SLiMS sebagai administrator (admin)
- [ ] Buka menu `system` >> `modules`
- [ ] Lalu klik menu `Add new Modules` dan isikan informasi yang dibutuhkan. `Module path` adalah nama folder yang sebelumnya dibuat (`plugins`)
- Silahkan simpan, logout dan login kembali. Maka module `plugins` sudah tersedia. Modifikasi lebih lanjut tergantung bagaimana anda ngodingnya.
