### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by agungsugiarto** [slims/slims8_akasia#68]
Apakah ada EER Diagram untuk database slims8_akasia ?
saya ingin melihat relasi antar table agar lebih mudah memahami. Terimakasih

**Comment by buitenzorg812** [comment]
sudah coba lihat yang ini, mas? memang berdasarkan versi senayan 3-stablem, tapi sebagian besar masih mengacu ke kerangka ini.

https://github.com/slims/s3-devdocs

**Comment by aditya0909** [comment]
Apakah sudah ada yang pernah login Slims akasia pakai LDAP ?
saya sudah mencoba dan selalu ada message **"username / password salah"**
mohon pencerahannya

terima kasih

**Comment by agungsugiarto** [comment]
@buitenzorg812 terima kasih om, akan saya jadikan referensi untuk saya belajar
