### ISSUE TITLE
editing/deleting "RDA Media Type" and "RDA Carrier Type" doesn't work correctly

### ISSUE THREAD

**Issue by matlam** [slims/slims8_akasia#7]
There are multiple issues with editing and deleting items from the "RDA Media Type" and "RDA Carrier Type" in the master_file module
- deleting doesn't work(there is a message that deleting was successful, but the items are still there)
- after saving an item you see the list of "RDA Content Type" even if you edit/create a Media or Carrier item
- editing creates a new item instead of updating the existing one

**Comment by dicarve** [comment]
Thank you for your report matlam, we will investigating  the issues and update the repository after the fixes done

**Comment by matlam** [comment]
Thanks for looking into this issue. It is mostly fixed now.

> after saving an item you see the list of "RDA Content Type" even if you edit/create a Media or Carrier item

But this is still not working completely. When creating a new "RDA Carrier Type" or "RDA Media Type" you are shown the list of  "RDA Content Type". The same happens when deleting from the detail view. Editing is working now though.
