### ISSUE TITLE
Thumbnail Cover Tidak Bisa Tampil

### ISSUE THREAD

**Issue by hasansaifulrijal** [slims/slims8_akasia#74]
Thumbnail Cover Promote Book pada halaman Home bisa tampil, namun pada hasil pencarian dan detail book cover tidak bisa tampil. Kendala ini muncul ketika SLiMS dipasang di hosting.

![capture1](https://user-images.githubusercontent.com/34324177/33693093-510420ac-db23-11e7-8e0a-9c98a4c84d45.PNG)

![capture3](https://user-images.githubusercontent.com/34324177/33693238-4c97c072-db24-11e7-9c07-8d9b7f3392db.png)

Saya sudah mencoba melakukan modifikasi pada file .htaccess dengan menambahkan kode berikut:
```
# Modifikasi ketika gambar cover tidak bisa tampil
<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>
```

tapi OPAC tetap tidak bisa menampilkan thumbnail cover..
Mohon pencerahannya...

**Comment by ndutndutan** [comment]
mas.. apakah ini sudah solved?
