### ISSUE TITLE
Aturan Peminjaman (Loan Rules) tidak bekerja

### ISSUE THREAD

**Issue by kathleenazali** [slims/slims8_akasia#79]
Halo, saya barusan membuat periode peminjaman dari 14 hari menjadi 21 hari. Namun meski saya ubah, dan bahkan saya coba hapus aturan peminjaman yang lama2, tetap saja tanggal harus kembali yang muncul 14 hari dari tanggal peminjaman. Tanggal harus kembali harus diubah secara manual agar menjadi 21 hari. Kira2 kenapa ya?

![screen shot 2018-01-08 at 15 06 13](https://user-images.githubusercontent.com/11498979/34663094-82ff7836-f487-11e7-97ff-ea1a57f2f157.png)

![screen shot 2018-01-08 at 15 06 57](https://user-images.githubusercontent.com/11498979/34663098-89a806c6-f487-11e7-8c48-e34b62633515.png)

**Comment by slims** [comment]
@kathleenazali Aturan peminjaman yang baru baru akan berdampak kepada transaksi yang dilakukan setelah aturan peminjaman terbaru diberlakukan. Yang lama tetap tercatat dengan masa peminjaman aturan peminjaman yang lama.

**Comment by kathleenazali** [comment]
Terimakasih @slims. Namun ini sebetulnya transaksi baru, yang dilakukan setelah aturan peminjaman terbaru diberlakukan. Tetap tidak mau berubah menjadi 21 hari.

**Comment by slims** [comment]
@kathleenazali Berarti loan rules yg di set tdk meencakup user yg mslakukan transaksi

**Comment by kathleenazali** [comment]
Sudah, untuk semua user groups sudah disetel 21 hari, tapi tetap semua transaksi yang dilakukan tetap menerapkan 14 hari. 

![screen shot 2018-01-08 at 19 02 06](https://user-images.githubusercontent.com/11498979/34669924-a3878390-f4a6-11e7-8c8d-90643e2e7966.png)
Screenshot aturan peminjaman

![screen shot 2018-01-08 at 19 02 54](https://user-images.githubusercontent.com/11498979/34669950-c3e2891e-f4a6-11e7-9b5a-0f0acce2512f.png)
Screenshot peminjaman (dilakukan setelah setelan semua jenis anggota sudah disetel menjadi 21 hari, tapi tetap otomatis masih memasukkan 14 hari, 22 Januari 2018. Kalau 21 hari, semestinya 29 Januari 2018)

**Comment by slims** [comment]
@kathleenazali Coba tes bikin loan rules nya lebih spesifik. Membertype dan tipe koleksinya nya jangan dikosongin.

**Comment by kathleenazali** [comment]
Sebetulnya sebelumnya tipe koleksi tidak saya kosongi sih, tapi saya masukkan "SEMUA". Ini saya coba ganti tipe koleksinya, dan sekarang bisa, untuk tipe koleksi yang relevan. 

![screen shot 2018-01-08 at 19 21 28](https://user-images.githubusercontent.com/11498979/34670694-015f81ea-f4aa-11e7-8b77-d6c0e4bc9a25.png)
Tapi ini berarti kategori "SEMUA" dalam tipe koleksi tidak bekerja ya?

![screen shot 2018-01-08 at 19 29 07](https://user-images.githubusercontent.com/11498979/34670742-3b482448-f4aa-11e7-8792-c5d5563a8743.png)
Kalau tipe koleksi diganti menjadi spesifik satu kategori baru bisa. Jadi harus masukkan satu2 untuk tiap kategori.

**Comment by slims** [comment]
@kathleenazali Betul. Setahu saya harus spesifik.
