### ISSUE TITLE
Gagal transaksi di Sirkulasi (Pengembalian buku gagal)

### ISSUE THREAD

**Issue by ghost** [slims/slims8_akasia#80]
Dear Slims

mohon dibantu, untuk slims8 akasia terdapat error pada sirkulasi, yaitu ketika buku dikembalikan, keterangan sudah sukses tp peminjaman tetap muncul. apakah ada solusinya?

 
![image](https://user-images.githubusercontent.com/35447585/34932640-38f07658-fa06-11e7-8765-0e332ed7d22c.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/35447585/34932754-ca4c1b34-fa06-11e7-95d8-81aa6de4bdd9.png)

Gagal tambah peminjaman

**Comment by slims** [comment]
@caturfp Apakah sudah dilakukan upgrade tabel sql akasia?

**Comment by ghost** [comment]
saya menggunakan db slim7 pak, upgrade ketika install slim8. apakah ada prosedur lainnya untuk upgrade?

**Comment by slims** [comment]
@caturfp Coba db slims7nya diupgrade menggunakan db akasia

**Comment by slims** [comment]
@caturfp Sepertinya proses upgrade nya belum sempurna. Struktur database nya diupdate juga kah?
