### ISSUE TITLE
Insert flipbook

### ISSUE THREAD

**Issue by chandraes** [slims/slims8_akasia#84]
Bisa kah slims ini untuk insert flipbook??

**Comment by buitenzorg812** [comment]
@eigernick bisa. silahkan kontak komunitas slims banten untuk mendapatkan plugin flipbook

**Comment by desawarna** [comment]
Bisa 😁

Pada tanggal 31 Jan 2018 1.03 PM, "Arif Syamsudin" <notifications@github.com>
menulis:
