### ISSUE TITLE
Slims 8.3.1 cannot create new system user

### ISSUE THREAD

**Issue by dbrw** [slims/slims8_akasia#91]
I've managed to install fresh slims with this configuration:
- Maria DB version 5.5.5-10.1.26-MariaDB-0+deb9u1
- PHP PHP 7.0.19-1
- nginx 1.10.3

When I try to create new librarian on system - Librarian & System Users - add new user. After I filled up all the field and press save, the browser seems reloading the page but nothing else happend. I checked on the database, no user been added.

This behaviour also happend on User Group page.

Any other suggestion on this matters?

**Comment by putradimas** [comment]
Try to use php 5.6

**Comment by dbrw** [comment]
managed to solve the problem by using apache web server, PHP version seems doesn't affecting this behaviour.
